#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_adresse:
  path: /api/adresse
  controller: App\Controller\Address\AddressApiController::getAddressByStreetChunk
  methods: POST

api_adresse_get:
  path: /api/adresseget
  controller: App\Controller\Address\AddressApiController::getAddressByStreetChunk
  methods: GET