#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_address_search:
  path: /api/adresse
  controller: App\Controller\Address\AddressApiController::searchAddress
  methods: POST